### ISSUE TITLE
Need to split work with transactions and categories to different storage and handler

### ISSUE THREAD

**Issue by markelrep** [lungria/spendshelf-backend#34]
At this moment, we have one storage that works with transactions table and category table, and handler` transaction.go` implements all methods from the storage. To my mind, if we split these into different storage and handler it will help us to more faster grow API and code will be cleaner. What do you think about it?

**Comment by SuddenGunter** [comment]
storage was split in https://github.com/lungria/spendshelf-backend/pull/50
I have not split the handler, because it routes seems very native: /transactions and /transactions/categories - not any categories, but the categories of transactions
